apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-db-pvc
  namespace: firefly-iii
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-upload-pvc
  namespace: firefly-iii
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
