apiVersion: v1
kind: Secret
metadata:
  name: firefly-iii-secrets
  namespace: firefly-iii
type: Opaque
stringData:
  # IMPORTANT: Change these values in production!
  APP_KEY: "base64:yT5ZdxtwSlSJYb6wh5DAarhxD55ZElBIADVEBYgZOTQ=" # Laravel base64 encoded key
  DB_PASSWORD: "firefly-db-password"
  STATIC_CRON_TOKEN: "LX5J+2X6Wa0yS+DZq1fOB9Cb7m97xj95"
