apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Validate=true
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  selfSigned: {}
