# Proxmox CSI Plugin Secret
# INSTRUCTIONS: Fill in your Proxmox details, then apply with:
# kubectl apply -f proxmox-csi-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
type: Opaque
stringData:
  config.yaml: |
    clusters:
      - url: https://192.168.1.10:8006/api2/json
        insecure: true
        token_id: "root@pam!csi"
        token_secret: "07402913-298a-4f47-9ac7-4bafeee606ba"
        region: pve
